# See https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
dist: xenial

language: scala

addons:
  hostname: localhost

services:
  - docker

jdk:
  - openjdk8

scala:
  - "2.11.12"
  - "2.12.10"

before_install:
  - docker run -d --restart=always -p 9091:9000 -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=password minio/minio:RELEASE.2019-05-02T19-07-09Z server /data

before_cache:
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt            -name "*.lock"               -type f -delete
  - find $HOME/.coursier/cache -name "*.lock"               -type f -delete

cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt
   - $HOME/.couriser

script:
  - .travis/run.sh

notifications:
  email:
    recipients:
      - lossyrob@gmail.com
      - echeipesh@gmail.com
      - gr.pomadchin@gmail.com
  slack:
    rooms:
      secure: jsY+v/UWRwknxzxuOt3SWUXmfhVm5yE1v1sMtZqM+Vag6vUb8E+oL9XfGYbn7AmYcViP5ZsLPU88rZqwwHg5GgWKfD+34r3C2ZxG+zRybm9q1m3VwsG/ykmHrK47wuSiqBoX4/0rcX86drtL413gQ3bKWt7Vl80ff0AVCw/3wSnQjcHHvfJLBhwUpwD8AX791E8/ITT98+B1+kaIt1Lw13QJ1MsoiIuB8KnfRABA4DIuRkXPAWwr3zt0dcwHqIfrow97KodHQnLr19VU9D7Rfv6pDGRBSMTObXh1/z/4Lk5k+4oDXJhH6wzDDAi5w/2/fb9q0tphx/XCUHolYIJDVNokkJRfoLrvwn2a8iAI/rfqDVjM8nnVIIlYhuodSrlJvgzig7IMCVo4qIp31XJNzNlI5D7OK8Vm7VBEVhm1rUt+d9+oz5vN4KXk4lozQ37vNmRdZzdqvEAeuHWcOSZ/HJE7TG8josCXK/TIvI14wZ+xguPqUlEuHs21EIQQzDxL1pD8VW+DXPvzKca/ZeH+BSYyHHzW+ijkT/Yyr8aGfbofp2aXrLHZdelYejPSHdgiOZVnQcFdMjIqPYHWwHe6V/lo7QvYlbwMg98432Sgne6GKUy96hMT3JHxRKG7E+6XpJ3g4d2U4B286Td1Vbm0pu1hV0HRdrYkgkSO3w1UWC4=

before_deploy:
  - export VERSION_SUFFIX="-${TRAVIS_COMMIT:0:7}"

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: geotrellis/geotrellis-pointcloud
      branch: master
      jdk: openjdk8

after_deploy:
  - rm -f "${HOME}/.bintray/.credentials"
