name: GeoTrellis PointCloud CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.10, 2.11.12]

    container:
      image: daunnc/pdal-ubuntu:2.1.0

    services:
      minio:
        image: bitnami/minio:2020.5.16
        env:
          _JAVA_OPTIONS: "-Xms1m -Xmx512m"
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: password
        ports:
          - 9091:9000
        # options: >-
        #   --health-cmd "curl -f http://localhost:9091/minio/health/live"
        #   --health-interval 30s
        #   --health-timeout 20s
        #   --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Test
        run: |
          ./sbt ++${{matrix.scala}} version
          ./sbt ++${{matrix.scala}} "project pointcloud" test
